---
title: Encendiendo un led con ESP32
author: Luis Mendoza
date: '2021-08-15'
slug: encendiendo-un-led-con-esp32
categories: []
tags:
  - ArduinoIDE
  - ESP32
  - IoT
subtitle: ''
summary: ''
authors: []
lastmod: '2021-08-15T18:10:05-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

La lista de materiales, el circuito y el código son básicamente los mismos que en Arduino.

## Materiales

- Led de color indistinto

- Resistencia de al menos 220$\Omega$

- Tablilla de prototipado

- ESP32

## Circuito

Armamos el circuito conectando la patilla corta del led a la resistencia y ésta a su vez a la tierra GND de la ESP32 (pin superior derecho, observando la placa con el puerto micro-usb apuntando hacia abajo). La patilla larga del led se conecta al pin 23 (se encuentra al lado del pin de tierra) 

## Código

```{C++}
// Descomentar la siguiente línea si no se utiliza Arduino IDE
// #include <Arduino.h> 

const int led = 23;

void setup() {
    pinMode(led, OUTPUT);
}

void loop() {
    digitalWrite(led, HIGH);   
    delay(1000);                 
    digitalWrite(led, LOW);    
    delay(1000)
}
```

## Sobre cierto error de comunicación

Anteriormente ya se mencionó pero cabe repetirlo. La placa NodeMCU-32S tiene algo peculiar. Si al momento de subir un _sketch_ no se presiona el botón _BOOT_ ocurrirá un error de comunicación. Por lo tanto, al momento de enviar el archivo a la placa, presione dicho botón hasta que la terminal indique que se está escribiendo en la placa. Si no ha surgido el error, presione el otro botón de la placa (EN) para activar el modo _ejecución_. Sería todo.



